// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc_trainer

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Trainer Context Queries
	// Purpose: CRUD operations for trainer_hours table
	CreateHour(ctx context.Context, iD pgtype.UUID, hourTime time.Time, availability string) (TrainerHour, error)
	DeleteHour(ctx context.Context, id pgtype.UUID) error
	GetHour(ctx context.Context, id pgtype.UUID) (TrainerHour, error)
	GetHourByTime(ctx context.Context, hourTime time.Time) (TrainerHour, error)
	ListHours(ctx context.Context, createdAt time.Time, iD pgtype.UUID, limit int32) ([]TrainerHour, error)
	ListHoursByTimeRange(ctx context.Context, hourTime time.Time, hourTime_2 time.Time) ([]TrainerHour, error)
	UpdateHourAvailability(ctx context.Context, iD pgtype.UUID, availability string) error
}

var _ Querier = (*Queries)(nil)
