// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: trainer.sql

package sqlc_trainer

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createHour = `-- name: CreateHour :one

INSERT INTO trainer_hours (
    id,
    hour_time,
    availability,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, NOW(), NOW()
) RETURNING id, hour_time, availability, created_at, updated_at
`

// Trainer Context Queries
// Purpose: CRUD operations for trainer_hours table
func (q *Queries) CreateHour(ctx context.Context, iD pgtype.UUID, hourTime time.Time, availability string) (TrainerHour, error) {
	row := q.db.QueryRow(ctx, createHour, iD, hourTime, availability)
	var i TrainerHour
	err := row.Scan(
		&i.ID,
		&i.HourTime,
		&i.Availability,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteHour = `-- name: DeleteHour :exec
DELETE FROM trainer_hours
WHERE id = $1
`

func (q *Queries) DeleteHour(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteHour, id)
	return err
}

const getHour = `-- name: GetHour :one
SELECT id, hour_time, availability, created_at, updated_at FROM trainer_hours
WHERE id = $1
`

func (q *Queries) GetHour(ctx context.Context, id pgtype.UUID) (TrainerHour, error) {
	row := q.db.QueryRow(ctx, getHour, id)
	var i TrainerHour
	err := row.Scan(
		&i.ID,
		&i.HourTime,
		&i.Availability,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHourByTime = `-- name: GetHourByTime :one
SELECT id, hour_time, availability, created_at, updated_at FROM trainer_hours
WHERE hour_time = $1
FOR UPDATE
`

func (q *Queries) GetHourByTime(ctx context.Context, hourTime time.Time) (TrainerHour, error) {
	row := q.db.QueryRow(ctx, getHourByTime, hourTime)
	var i TrainerHour
	err := row.Scan(
		&i.ID,
		&i.HourTime,
		&i.Availability,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listHours = `-- name: ListHours :many
SELECT id, hour_time, availability, created_at, updated_at FROM trainer_hours
WHERE (created_at > $1 OR $1 IS NULL)
  AND (id > $2 OR $2 IS NULL)
ORDER BY created_at, id
LIMIT $3
`

func (q *Queries) ListHours(ctx context.Context, createdAt time.Time, iD pgtype.UUID, limit int32) ([]TrainerHour, error) {
	rows, err := q.db.Query(ctx, listHours, createdAt, iD, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrainerHour
	for rows.Next() {
		var i TrainerHour
		if err := rows.Scan(
			&i.ID,
			&i.HourTime,
			&i.Availability,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHoursByTimeRange = `-- name: ListHoursByTimeRange :many
SELECT id, hour_time, availability, created_at, updated_at FROM trainer_hours
WHERE hour_time BETWEEN $1 AND $2
ORDER BY hour_time
`

func (q *Queries) ListHoursByTimeRange(ctx context.Context, hourTime time.Time, hourTime_2 time.Time) ([]TrainerHour, error) {
	rows, err := q.db.Query(ctx, listHoursByTimeRange, hourTime, hourTime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrainerHour
	for rows.Next() {
		var i TrainerHour
		if err := rows.Scan(
			&i.ID,
			&i.HourTime,
			&i.Availability,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHourAvailability = `-- name: UpdateHourAvailability :exec
UPDATE trainer_hours
SET
    availability = $2,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateHourAvailability(ctx context.Context, iD pgtype.UUID, availability string) error {
	_, err := q.db.Exec(ctx, updateHourAvailability, iD, availability)
	return err
}
