// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc_trainings

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

// Trainer availability hours for scheduling
type TrainerHour struct {
	// Hour unique identifier
	ID pgtype.UUID `json:"id"`
	// The specific hour (truncated to hour boundary)
	HourTime time.Time `json:"hour_time"`
	// Availability status: available, not_available, or training_scheduled
	Availability string `json:"availability"`
	// Record creation timestamp for auditing and pagination
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// Training sessions scheduled by users with trainers
type TrainingsTraining struct {
	// Training unique identifier (domain UUID)
	ID pgtype.UUID `json:"id"`
	// User who booked the training
	UserID pgtype.UUID `json:"user_id"`
	// User name snapshot at booking time
	UserName     string    `json:"user_name"`
	TrainingTime time.Time `json:"training_time"`
	// Training notes, max 1000 characters
	Notes           *string            `json:"notes"`
	ProposedNewTime pgtype.Timestamptz `json:"proposed_new_time"`
	// Who proposed reschedule: trainer or attendee
	MoveProposedBy *string `json:"move_proposed_by"`
	Canceled       bool    `json:"canceled"`
	// Record creation timestamp for auditing and pagination
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// User accounts with roles (trainer or attendee)
type UsersUser struct {
	// User unique identifier
	ID pgtype.UUID `json:"id"`
	// User role: trainer or attendee
	UserType string `json:"user_type"`
	// User full name
	Name string `json:"name"`
	// User email address (optional, for future authentication)
	Email   *string `json:"email"`
	Balance int32   `json:"balance"`
	LastIp  *string `json:"last_ip"`
	// Record creation timestamp for auditing and pagination
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
