// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc_trainings

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Trainings Context Queries
	// Purpose: CRUD operations for trainings_trainings table
	CreateTraining(ctx context.Context, iD pgtype.UUID, userID pgtype.UUID, userName string, trainingTime time.Time, notes *string, proposedNewTime pgtype.Timestamptz, moveProposedBy *string, canceled bool) (TrainingsTraining, error)
	DeleteTraining(ctx context.Context, id pgtype.UUID) error
	GetTraining(ctx context.Context, id pgtype.UUID) (TrainingsTraining, error)
	ListAllTrainings(ctx context.Context) ([]TrainingsTraining, error)
	ListTrainingsByUser(ctx context.Context, userID pgtype.UUID, createdAt time.Time, iD pgtype.UUID, limit int32) ([]TrainingsTraining, error)
	UpdateTraining(ctx context.Context, iD pgtype.UUID, notes *string, proposedNewTime pgtype.Timestamptz, moveProposedBy *string, canceled bool) error
}

var _ Querier = (*Queries)(nil)
