// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: trainings.sql

package sqlc_trainings

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTraining = `-- name: CreateTraining :one

INSERT INTO trainings_trainings (
    id,
    user_id,
    user_name,
    training_time,
    notes,
    proposed_new_time,
    move_proposed_by,
    canceled,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, NOW(), NOW()
) RETURNING id, user_id, user_name, training_time, notes, proposed_new_time, move_proposed_by, canceled, created_at, updated_at
`

// Trainings Context Queries
// Purpose: CRUD operations for trainings_trainings table
func (q *Queries) CreateTraining(ctx context.Context, iD pgtype.UUID, userID pgtype.UUID, userName string, trainingTime time.Time, notes *string, proposedNewTime pgtype.Timestamptz, moveProposedBy *string, canceled bool) (TrainingsTraining, error) {
	row := q.db.QueryRow(ctx, createTraining,
		iD,
		userID,
		userName,
		trainingTime,
		notes,
		proposedNewTime,
		moveProposedBy,
		canceled,
	)
	var i TrainingsTraining
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UserName,
		&i.TrainingTime,
		&i.Notes,
		&i.ProposedNewTime,
		&i.MoveProposedBy,
		&i.Canceled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTraining = `-- name: DeleteTraining :exec
DELETE FROM trainings_trainings
WHERE id = $1
`

func (q *Queries) DeleteTraining(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTraining, id)
	return err
}

const getTraining = `-- name: GetTraining :one
SELECT id, user_id, user_name, training_time, notes, proposed_new_time, move_proposed_by, canceled, created_at, updated_at FROM trainings_trainings
WHERE id = $1
`

func (q *Queries) GetTraining(ctx context.Context, id pgtype.UUID) (TrainingsTraining, error) {
	row := q.db.QueryRow(ctx, getTraining, id)
	var i TrainingsTraining
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UserName,
		&i.TrainingTime,
		&i.Notes,
		&i.ProposedNewTime,
		&i.MoveProposedBy,
		&i.Canceled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllTrainings = `-- name: ListAllTrainings :many
SELECT id, user_id, user_name, training_time, notes, proposed_new_time, move_proposed_by, canceled, created_at, updated_at FROM trainings_trainings
ORDER BY created_at DESC, id
`

func (q *Queries) ListAllTrainings(ctx context.Context) ([]TrainingsTraining, error) {
	rows, err := q.db.Query(ctx, listAllTrainings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrainingsTraining
	for rows.Next() {
		var i TrainingsTraining
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserName,
			&i.TrainingTime,
			&i.Notes,
			&i.ProposedNewTime,
			&i.MoveProposedBy,
			&i.Canceled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrainingsByUser = `-- name: ListTrainingsByUser :many
SELECT id, user_id, user_name, training_time, notes, proposed_new_time, move_proposed_by, canceled, created_at, updated_at FROM trainings_trainings
WHERE user_id = $1
  AND (created_at > $2 OR $2 IS NULL)
  AND (id > $3 OR $3 IS NULL)
ORDER BY created_at, id
LIMIT $4
`

func (q *Queries) ListTrainingsByUser(ctx context.Context, userID pgtype.UUID, createdAt time.Time, iD pgtype.UUID, limit int32) ([]TrainingsTraining, error) {
	rows, err := q.db.Query(ctx, listTrainingsByUser,
		userID,
		createdAt,
		iD,
		limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrainingsTraining
	for rows.Next() {
		var i TrainingsTraining
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserName,
			&i.TrainingTime,
			&i.Notes,
			&i.ProposedNewTime,
			&i.MoveProposedBy,
			&i.Canceled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTraining = `-- name: UpdateTraining :exec
UPDATE trainings_trainings
SET
    notes = COALESCE($2, notes),
    proposed_new_time = COALESCE($3, proposed_new_time),
    move_proposed_by = COALESCE($4, move_proposed_by),
    canceled = COALESCE($5, canceled),
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateTraining(ctx context.Context, iD pgtype.UUID, notes *string, proposedNewTime pgtype.Timestamptz, moveProposedBy *string, canceled bool) error {
	_, err := q.db.Exec(ctx, updateTraining,
		iD,
		notes,
		proposedNewTime,
		moveProposedBy,
		canceled,
	)
	return err
}
