// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc_users

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Users Context Queries
	// Purpose: CRUD operations for users_users table
	CreateUser(ctx context.Context, iD pgtype.UUID, userType string, name string, email *string, column5 interface{}) (UsersUser, error)
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	GetUser(ctx context.Context, id pgtype.UUID) (UsersUser, error)
	GetUserByEmail(ctx context.Context, email *string) (UsersUser, error)
	ListUsersByType(ctx context.Context, userType string, createdAt time.Time, iD pgtype.UUID, limit int32) ([]UsersUser, error)
	UpdateBalance(ctx context.Context, iD pgtype.UUID, balance int32) error
	UpdateLastIP(ctx context.Context, iD pgtype.UUID, lastIp *string) error
	UpdateUser(ctx context.Context, iD pgtype.UUID, name string, email *string) error
}

var _ Querier = (*Queries)(nil)
