// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc_users

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one

INSERT INTO users_users (
    id,
    user_type,
    name,
    email,
    balance,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, COALESCE($5, 0), NOW(), NOW()
) RETURNING id, user_type, name, email, balance, last_ip, created_at, updated_at
`

// Users Context Queries
// Purpose: CRUD operations for users_users table
func (q *Queries) CreateUser(ctx context.Context, iD pgtype.UUID, userType string, name string, email *string, column5 interface{}) (UsersUser, error) {
	row := q.db.QueryRow(ctx, createUser,
		iD,
		userType,
		name,
		email,
		column5,
	)
	var i UsersUser
	err := row.Scan(
		&i.ID,
		&i.UserType,
		&i.Name,
		&i.Email,
		&i.Balance,
		&i.LastIp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users_users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, user_type, name, email, balance, last_ip, created_at, updated_at FROM users_users
WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id pgtype.UUID) (UsersUser, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i UsersUser
	err := row.Scan(
		&i.ID,
		&i.UserType,
		&i.Name,
		&i.Email,
		&i.Balance,
		&i.LastIp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, user_type, name, email, balance, last_ip, created_at, updated_at FROM users_users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email *string) (UsersUser, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i UsersUser
	err := row.Scan(
		&i.ID,
		&i.UserType,
		&i.Name,
		&i.Email,
		&i.Balance,
		&i.LastIp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsersByType = `-- name: ListUsersByType :many
SELECT id, user_type, name, email, balance, last_ip, created_at, updated_at FROM users_users
WHERE user_type = $1
  AND (created_at > $2 OR $2 IS NULL)
  AND (id > $3 OR $3 IS NULL)
ORDER BY created_at, id
LIMIT $4
`

func (q *Queries) ListUsersByType(ctx context.Context, userType string, createdAt time.Time, iD pgtype.UUID, limit int32) ([]UsersUser, error) {
	rows, err := q.db.Query(ctx, listUsersByType,
		userType,
		createdAt,
		iD,
		limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsersUser
	for rows.Next() {
		var i UsersUser
		if err := rows.Scan(
			&i.ID,
			&i.UserType,
			&i.Name,
			&i.Email,
			&i.Balance,
			&i.LastIp,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBalance = `-- name: UpdateBalance :exec
UPDATE users_users
SET
    balance = balance + $2,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateBalance(ctx context.Context, iD pgtype.UUID, balance int32) error {
	_, err := q.db.Exec(ctx, updateBalance, iD, balance)
	return err
}

const updateLastIP = `-- name: UpdateLastIP :exec
UPDATE users_users
SET
    last_ip = $2,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateLastIP(ctx context.Context, iD pgtype.UUID, lastIp *string) error {
	_, err := q.db.Exec(ctx, updateLastIP, iD, lastIp)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users_users
SET
    name = COALESCE($2, name),
    email = COALESCE($3, email),
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateUser(ctx context.Context, iD pgtype.UUID, name string, email *string) error {
	_, err := q.db.Exec(ctx, updateUser, iD, name, email)
	return err
}
