// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: trainer.proto

package trainer

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IsHourAvailableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsHourAvailableRequest) Reset() {
	*x = IsHourAvailableRequest{}
	mi := &file_trainer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsHourAvailableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsHourAvailableRequest) ProtoMessage() {}

func (x *IsHourAvailableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trainer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsHourAvailableRequest.ProtoReflect.Descriptor instead.
func (*IsHourAvailableRequest) Descriptor() ([]byte, []int) {
	return file_trainer_proto_rawDescGZIP(), []int{0}
}

func (x *IsHourAvailableRequest) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

type IsHourAvailableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsAvailable   bool                   `protobuf:"varint,1,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsHourAvailableResponse) Reset() {
	*x = IsHourAvailableResponse{}
	mi := &file_trainer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsHourAvailableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsHourAvailableResponse) ProtoMessage() {}

func (x *IsHourAvailableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trainer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsHourAvailableResponse.ProtoReflect.Descriptor instead.
func (*IsHourAvailableResponse) Descriptor() ([]byte, []int) {
	return file_trainer_proto_rawDescGZIP(), []int{1}
}

func (x *IsHourAvailableResponse) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

type UpdateHourRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateHourRequest) Reset() {
	*x = UpdateHourRequest{}
	mi := &file_trainer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateHourRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHourRequest) ProtoMessage() {}

func (x *UpdateHourRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trainer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHourRequest.ProtoReflect.Descriptor instead.
func (*UpdateHourRequest) Descriptor() ([]byte, []int) {
	return file_trainer_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateHourRequest) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

var File_trainer_proto protoreflect.FileDescriptor

const file_trainer_proto_rawDesc = "" +
	"\n" +
	"\rtrainer.proto\x12\atrainer\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"H\n" +
	"\x16IsHourAvailableRequest\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\"<\n" +
	"\x17IsHourAvailableResponse\x12!\n" +
	"\fis_available\x18\x01 \x01(\bR\visAvailable\"C\n" +
	"\x11UpdateHourRequest\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time2\xc5\x02\n" +
	"\x0eTrainerService\x12V\n" +
	"\x0fIsHourAvailable\x12\x1f.trainer.IsHourAvailableRequest\x1a .trainer.IsHourAvailableResponse\"\x00\x12H\n" +
	"\x10ScheduleTraining\x12\x1a.trainer.UpdateHourRequest\x1a\x16.google.protobuf.Empty\"\x00\x12F\n" +
	"\x0eCancelTraining\x12\x1a.trainer.UpdateHourRequest\x1a\x16.google.protobuf.Empty\"\x00\x12I\n" +
	"\x11MakeHourAvailable\x12\x1a.trainer.UpdateHourRequest\x1a\x16.google.protobuf.Empty\"\x00BFZDgithub.com/vaintrub/go-ddd-template/internal/common/genproto/trainerb\x06proto3"

var (
	file_trainer_proto_rawDescOnce sync.Once
	file_trainer_proto_rawDescData []byte
)

func file_trainer_proto_rawDescGZIP() []byte {
	file_trainer_proto_rawDescOnce.Do(func() {
		file_trainer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trainer_proto_rawDesc), len(file_trainer_proto_rawDesc)))
	})
	return file_trainer_proto_rawDescData
}

var file_trainer_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_trainer_proto_goTypes = []any{
	(*IsHourAvailableRequest)(nil),  // 0: trainer.IsHourAvailableRequest
	(*IsHourAvailableResponse)(nil), // 1: trainer.IsHourAvailableResponse
	(*UpdateHourRequest)(nil),       // 2: trainer.UpdateHourRequest
	(*timestamppb.Timestamp)(nil),   // 3: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),           // 4: google.protobuf.Empty
}
var file_trainer_proto_depIdxs = []int32{
	3, // 0: trainer.IsHourAvailableRequest.time:type_name -> google.protobuf.Timestamp
	3, // 1: trainer.UpdateHourRequest.time:type_name -> google.protobuf.Timestamp
	0, // 2: trainer.TrainerService.IsHourAvailable:input_type -> trainer.IsHourAvailableRequest
	2, // 3: trainer.TrainerService.ScheduleTraining:input_type -> trainer.UpdateHourRequest
	2, // 4: trainer.TrainerService.CancelTraining:input_type -> trainer.UpdateHourRequest
	2, // 5: trainer.TrainerService.MakeHourAvailable:input_type -> trainer.UpdateHourRequest
	1, // 6: trainer.TrainerService.IsHourAvailable:output_type -> trainer.IsHourAvailableResponse
	4, // 7: trainer.TrainerService.ScheduleTraining:output_type -> google.protobuf.Empty
	4, // 8: trainer.TrainerService.CancelTraining:output_type -> google.protobuf.Empty
	4, // 9: trainer.TrainerService.MakeHourAvailable:output_type -> google.protobuf.Empty
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_trainer_proto_init() }
func file_trainer_proto_init() {
	if File_trainer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trainer_proto_rawDesc), len(file_trainer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_trainer_proto_goTypes,
		DependencyIndexes: file_trainer_proto_depIdxs,
		MessageInfos:      file_trainer_proto_msgTypes,
	}.Build()
	File_trainer_proto = out.File
	file_trainer_proto_goTypes = nil
	file_trainer_proto_depIdxs = nil
}
